apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fx4aa606l-java-springboot
  janus-idp.io/tekton: fx4aa606l-java-springboot
  backstage.io/kubernetes-id: fx4aa606l-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fx4aa606l-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
